# Home Assistant development config for Control4 Dimmers

# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.control4_dimmers: debug

# https://www.home-assistant.io/integrations/mqtt/
mqtt:
  broker: localhost
  port: 1883
